stages:
  train:
    cmd: python src/train.py experiment=catdog_ex +trainer.log_every_n_steps=5
    deps:
    - configs/experiment/catdog_ex.yaml
    - src/train.py
    - data/catdog
    outs:
    - logs:
        cache: false