defaults:
  - _self_
  - data: catdog
  - model: timm_classify
  - paths: default
  - trainer: default
  - hydra: default

task_name: "eval"

ckpt_path: ${paths.root_dir}/checkpoints/best_model.ckpt

# Evaluation specific settings
batch_size: 16
num_workers: 2

hydra:
  run:
    dir: ${paths.log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${paths.log_dir}/multiruns/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
